name: Qt mingw64 build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:                  
      # - uses: actions/checkout@v4      
      #   with:
      #     repository: 'llvm/llvm-project'
      #     ref: 'llvmorg-19.1.1' # specify the tag here
      #     path: 'llvm-project'
  
      - uses: actions/checkout@v4
      - name: build Clang shared       
        shell: cmd
        run: call build_clazy.bat shared

      - name: publish clang shared build
        uses:  actions/upload-artifact@v4
        with:
          name: libclang-shared.7z
          path: libclang.7z
          compression-level: 0 

  release:
      runs-on: windows-latest
      needs: build

      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'libclang-shared.7z'
          path: ./

      - name: Upload to Release
        id: upload_to_release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.7z"
          tag_name: test_0.01


      # - name: Prepare GitHub Release artifacts
      #   run: |
      #     echo ::set-output name=FILE_NAME::libclang-static.7z >> $GITHUB_ENVIRONMENT_VARIABLES
      #     echo ::set-output name=RELEASE_TITLE::"Release libclang-static.7z"
      #     echo ::set-output name=RELEASE_DESCRIPTION::"Compiled Clang static library using GitHub Actions"

      #       - name: Create GitHub Release
      #         uses: actions/upload-artifact@v4
      #         with:
      #           name: "Release libclang-static.7z"
      #           path: libclang.7z
      
      # - name: Release Drafter
      #   uses: release-drafter/release-drafter@v6.0.0
      # - name: Checkout clazy
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'KDE/clazy'
      #     ref: 'v1.12'
      #     path: 'clazy'
  
      # - name: build Clazy
      #   uses: actions/checkout@v4
      #   shell: cmd
      #   run: call run.bat clazy  
          
  # build_arm64:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: |
  #         set CI_ANDROID_ABI=arm64-v8a
  #         call run.bat release

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_release_mingw64_arm64-v8a.tar.gz
  #         path: qt_release_mingw64.tar.gz
          
  # build_armeabi:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: |
  #         set CI_ANDROID_ABI=armeabi-v7a
  #         call run.bat release

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_release_mingw64_armeabi-v7a.tar.gz
  #         path: qt_release_mingw64.tar.gz
          
  # build_x86_64:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: |
  #         set CI_ANDROID_ABI=x86_64
  #         call run.bat release

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_release_mingw64_x86_64.tar.gz
  #         path: qt_release_mingw64.tar.gz
          
  # build_x86:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: |
  #         set CI_ANDROID_ABI=x86
  #         call run.bat release

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_release_mingw64_x86.tar.gz
  #         path: qt_release_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz

          
  # build_debug:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch dependencies and build Qt
  #       shell: cmd
  #       run: call run.bat debug

  #     - name: Upload Qt
  #       uses: actions/upload-artifact@v3.1.3
  #       with:
  #         name: qt_debug_mingw64.tar.gz
  #         path: qt_debug_mingw64.tar.gz

      # - name: Upload Qt+Docs
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: qt_release_mingw64_with_docs.tar.gz
      #     path: qt_release_mingw64_with_docs.tar.gz
